export const clientLogos = [
  {
    id: "logo-1",
    src: "/img/gisheh-logo-type.svg",
    alt: "گیشه ۷",
    link: "https://gisheh7.ir",
    width: 100,
    height: 40,
  },
  {
    id: "logo-2",
    src: "/img/drtarjomeh-logo.jpg",
    alt: "دکتر ترجمه",
    link: "https://drtarjomeh.ir",
    width: 60,
    height: 60,
  },
  {
    id: "logo-3",
    src: "/img/jorjani-logo.png",
    alt: "آیت الله جرجانی",
    link: "https://jorjanishahroodi.ir",
    width: 200,
    height: 80,
  },
  {
    id: "logo-4",
    src: "/img/i-motion.png",
    alt: "آی موشن",
    link: "https://i-motion.ir",
    width: 100,
    height: 60,
  },
  {
    id: "logo-5",
    src: "/img/cfpark-logo.png",
    alt: "پارک بازار",
    link: "https://cfpark.ir/home",
    width: 100,
    height: 40,
  },
];
