export const portfolioFilters = [
  { label: "همه", value: "all" },
  { label: "طراحی وب", value: "web-design" },
  { label: "تجارت الکترونیک", value: "ecommerce" },
  { label: "پورتال آموزشی", value: "education" },
];
export const portfolios = [
  {
    id: "portfolio-1",
    title: "وب‌سایت فروشگاهی",
    subtitle: "تجارت الکترونیک",
    categories: "تجارت الکترونیک، طراحی وب",
    filterCategories: ["ecommerce", "web-design"],
    image: {
      src: "/img/portfolios/1.jpg",
      alt: "وب‌سایت فروشگاهی",
      width: 430,
      height: 390,
    },
    link: "/portfolio/ecommerce",
  },
  {
    id: "portfolio-2",
    title: "وب‌سایت شرکتی",
    subtitle: "طراحی وب",
    categories: "طراحی وب، UI/UX",
    filterCategories: ["web-design"],
    image: {
      src: "/img/portfolios/2.jpg",
      alt: "وب‌سایت شرکتی",
      width: 430,
      height: 390,
    },
    link: "/portfolio/corporate",
  },
  {
    id: "portfolio-3",
    title: "پورتال آموزشی",
    subtitle: "آموزش آنلاین",
    categories: "پورتال آموزشی، طراحی وب",
    filterCategories: ["education", "web-design"],
    image: {
      src: "/img/portfolios/3.jpg",
      alt: "پورتال آموزشی",
      width: 430,
      height: 390,
    },
    link: "/portfolio/education",
  },
  {
    id: "portfolio-4",
    title: "وب‌سایت شخصی",
    subtitle: "طراحی وب",
    categories: "طراحی وب، ریسپانسیو",
    filterCategories: ["web-design"],
    image: {
      src: "/img/portfolios/4.jpg",
      alt: "وب‌سایت شخصی",
      width: 430,
      height: 390,
    },
    link: "/portfolio/personal",
  },
  {
    id: "portfolio-5",
    title: "فروشگاه مد",
    subtitle: "تجارت الکترونیک",
    categories: "تجارت الکترونیک، UI/UX",
    filterCategories: ["ecommerce"],
    image: {
      src: "/img/portfolios/5.jpg",
      alt: "فروشگاه مد",
      width: 430,
      height: 390,
    },
    link: "/portfolio/fashion",
  },
  {
    id: "portfolio-6",
    title: "پلتفرم یادگیری",
    subtitle: "آموزش آنلاین",
    categories: "پورتال آموزشی، طراحی وب",
    filterCategories: ["education", "web-design"],
    image: {
      src: "/img/portfolios/6.jpg",
      alt: "پلتفرم یادگیری",
      width: 430,
      height: 390,
    },
    link: "/portfolio/learning",
  },
];
